version: '3'

services:
  php-fpm:
    image: adhocore/phpfpm:7.4
    container_name: 'php-fpm'
    ports:
      - '9000:9000'
    volumes:
      - ./project/:/app
    working_dir: /app
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: 'nginx'
    ports:
      - "${NGINXHTTPPORT}:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    volumes:
      - ./project/:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - app-network
volumes:
  postgresql:
#Docker Networks
networks:
  app-network:
    driver: bridge
